// Package gcs is the native uos.Client driver for Google Cloud Storage.
// It targets the v0.1 frozen pkg/uos surface (architecture_plan §1) and
// implements every method on uos.Client by translating to/from
// cloud.google.com/go/storage.
//
// All exported types and methods carry doc comments so the package is
// directly usable from godoc; vendor SDK types stay confined to this
// directory per AGENTS.md ("no provider-specific public types in
// pkg/uos") and are reachable from caller code only via Client.As(target).
//
// Per the M4 milestone validation focus, this driver is the first
// non-S3-family member of the matrix. It does NOT plug GCS error codes
// into pkg/uos/s3common.MapCodeString (that table is reserved for the
// S3-compat wire dialect); GCS-specific Code-string handling lives in a
// LOCAL switch inside error_map.go. The shared s3common helpers used
// here are MapHTTPStatus, MapContextErr, IsRetryable, and
// LowerMetadataKeys — those are wire-protocol-agnostic.
//
// # Auth model
//
// GCS supports two auth schemes:
//
//   - AuthOAuth2 (default): the SDK's auth package handles ADC
//     (Application Default Credentials), Service Account JSON via
//     option.WithCredentialsFile / option.WithCredentialsJSON, or a
//     caller-supplied oauth2.TokenSource via option.WithTokenSource.
//   - AuthHMAC: GCS HMAC keys (created via the IAM API) work with the
//     S3-compatible XML endpoint via the same SignedURL machinery,
//     forwarded as GoogleAccessID + private key bytes.
//
// SignedURL requires a credential carrying a private signing key.
// Application Default Credentials backed by Compute Engine, GKE, or
// Workload Identity do NOT carry a key locally; in those cases
// Signer.SignURL returns ErrUnsupported{CapSignedURLRead/Write} with
// Reason="credential lacks signing key" so callers can dispatch on the
// frozen Capability set rather than parsing strings.
//
// # Multipart mapping
//
// GCS has NO S3-style multipart upload. The closest equivalent is
// Resumable Upload — a single session URL with chunked PUT requests
// against it. The driver maps MultipartService onto resumable uploads:
//
//   - Initiate creates an *storage.Writer wrapped behind a
//     session-handle struct stored in an in-process registry keyed by
//     UploadID (the SDK does not expose the resumable session URL
//     directly through the high-level API). UploadID is a synthetic
//     handle generated by the driver; it is opaque to callers and not
//     persisted across process restarts.
//   - UploadPart writes a chunk to the open Writer.
//   - Complete finalises by closing the Writer; the returned
//     *ObjectAttrs supplies ETag and Generation (mapped to VersionID).
//   - Abort closes the Writer with an error, which cancels the
//     resumable session.
//
// **Limitation** (logged in docs/provider_roadmap.md "Lessons (M4)"):
// the resumable-upload session lives only in the originating process.
// MultipartService.List returns an empty page; the unified contract's
// orphan-cleanup case will SKIP for GCS. Callers needing
// cross-process resumability must use the SDK's
// NewWriterFromAppendableObject path (preview API, gRPC-only) reached
// through Client.As(target).
//
// # Metadata semantics
//
// GCS metadata is a free-form map[string]string. Keys are not
// auto-lower-cased by the SDK; the driver lower-cases on both ingress
// (via s3common.LowerMetadataKeys) and egress to honor the unified
// pkg/uos.Metadata contract.
//
// # Versioning semantics
//
// GCS object versioning is generation-number-based. The bucket-level
// Versioning toggle decides whether old generations are retained on
// overwrite/delete; the per-object Generation int64 is presented to
// callers as VersionID (formatted as decimal). When the caller passes
// VersionID back in a Get/Head/Delete request, the driver parses it as
// int64 and stamps it via ObjectHandle.Generation(gen).
package gcs

import "github.com/slowfei/oss-client/pkg/uos/capability"

// capabilities returns the v1-frozen capability.Report for the GCS
// driver. Cell values mirror docs/provider_matrix.md (the "gcs"
// column); see footnotes 1 (signing-key gating), 5 (CapDirectGrant on
// non-Azure non-token vendors), 10 (Uniform vs Fine-grained ACL), and
// 12 (CapNativeMove everywhere) for the rationale.
//
// Drivers MUST populate every key returned by capability.All() per
// architecture_plan §7.2; missing keys would fail the contract suite's
// report_completeness case. Returning a fresh map per call keeps the
// caller free to mutate the returned report without affecting later
// calls into this driver.
func capabilities() capability.Report {
	return capability.Report{
		Items: map[capability.Capability]capability.CapabilityStatus{
			capability.CapBucketCRUD: {
				Availability: capability.Supported,
				Reason:       "GCS BucketHandle.Create / Attrs / Buckets iterator / Delete (project id required for Create / List)",
			},
			capability.CapObjectCRUD: {
				Availability: capability.Supported,
				Reason:       "GCS ObjectHandle.NewWriter / NewReader / Attrs / Delete / CopierFrom",
			},
			capability.CapListPrefixDelimiter: {
				Availability: capability.Supported,
				Reason:       "GCS Query.Prefix + Query.Delimiter via BucketHandle.Objects",
			},
			capability.CapRangeRead: {
				Availability: capability.Supported,
				Reason:       "GCS ObjectHandle.NewRangeReader(offset, length)",
			},
			capability.CapMultipartUpload: {
				Availability: capability.Supported,
				Reason:       "mapped onto GCS Resumable Upload (Writer-backed in-process session registry); see package doc 'Multipart mapping'",
			},
			capability.CapSignedURLRead: {
				Availability: capability.Conditional,
				Reason:       "requires a credential carrying a private signing key (Service Account JSON or HMAC); ADC backed by Compute Engine / GKE / Workload Identity has no local key — see provider_matrix.md footnote 1",
			},
			capability.CapSignedURLWrite: {
				Availability: capability.Conditional,
				Reason:       "requires a credential carrying a private signing key (Service Account JSON or HMAC); ADC backed by Compute Engine / GKE / Workload Identity has no local key — see provider_matrix.md footnote 1",
			},
			capability.CapDirectGrant: {
				Availability: capability.Unsupported,
				Reason:       "GCS issues writes via presigned URL (CapSignedURLWrite) — see provider_matrix.md footnote 5",
			},
			capability.CapObjectTagging: {
				Availability: capability.Supported,
				Reason:       "GCS object metadata serves as the tagging analog (ObjectAttrs.Metadata round-trip)",
			},
			capability.CapVersioning: {
				Availability: capability.Supported,
				Reason:       "GCS object versioning is generation-number-based; bucket-level VersioningEnabled toggles retention. VersionID round-trips as a decimal-encoded Generation int64. See package doc 'Versioning semantics'",
			},
			capability.CapObjectACL: {
				Availability: capability.Conditional,
				Reason:       "GCS Uniform Bucket-Level Access disables per-object ACL writes; Fine-grained access mode permits them. The driver returns ErrPermissionDenied at call time when the bucket is in Uniform mode — see provider_matrix.md footnote 10",
			},
			capability.CapManagedEncryption: {
				Availability: capability.Supported,
				Reason:       "GCS server-side encryption is on by default (Google-managed keys); CMEK via ObjectAttrs.KMSKeyName at write time; CSEK via ObjectHandle.Key([]byte)",
			},
			capability.CapNativeMove: {
				Availability: capability.ExtensionOnly,
				Reason:       "GCS ObjectHandle.Move exists but is HNS-only (Hierarchical Namespace buckets); flat buckets fall back to Copy+Delete. Reach via As(target) for the HNS path — see provider_matrix.md footnote 12",
			},
		},
	}
}
